In [51]:
with open("/Users/shasshanksethuraman/Desktop/fastq.txt") as f:
  seq=f.readlines()

# IMPORTS

In [52]:
import numpy as np
from termcolor import colored
import random
from itertools import permutations

# Storing Protein and PHRED scores in one variable

In [53]:
S=[] #storing the individual DNA strings
P=[] #storing corresponding quality score for each DNA character
for i in seq[1::4]:
  S.append(i)
for j in seq[5::4]:#FINAL STRING

  P.append(j)

In [54]:
for i in range(len(S)):
  S[i]=S[i].strip('\n')
final_S=''
for i in S:
  final_S+=i
print(len(final_S))

4107879


In [43]:
#storing corresponding base cell accuracy for each DNA character
l_bca=[]

for i in range(len(P)):
  l=[]
  for v in P[i]:
    if v not in "\n":
      v=ord(v)-33
      l.append(round(100-(10**((-1)*int(v)/10)*100),2))
  l_bca.append(l)
t=[]
for i in l_bca:
  for j in i:
    t.append(j)
print(t)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



# NumPy Array of PHRED base cell accuracies

In [44]:
#list as a NumPy array

final_P=np.array(t)

print(final_P)

[ 99.98  99.94 100.   ...  99.98 100.    99.96]


# Function to generate RANDOM ministring

In [45]:
"""
@param n: user defined length of ministring 
"""

def generate_mini(n):
  ministr=''
  for j in range(n):
    ministr+=random.choice("ATGC")
  return (ministr)


length_mini=int(input('Enter preferred length of Mini string : ')) #length of ministring
ministr=generate_mini(length_mini) #ministring 
print(ministr)

Enter preferred length of Mini string : 5
TAATG


# Task 1

In [46]:
"""
Matching the dna sequences directly in order to distinguish between them based on base cell accuracy. 

@param r: Master string
@param m: Randomly generated mini string of user defined length
@param p: Array of PHRED quality scores
@param t: Threshold value for accuracy of match

"""

def directMatch(r, m, p,t):
  temp=[]
  results=[]
 
  d=r.count(m)
  print('Number of matches : ', d)

  i=-1
  while d!=0:
    index=r.find(m,i+1)
    i=index
    if index not in temp:
      temp.append(index)
    d=d-1

  check=True
  for j in temp:
    bsa=str(p[j:j+length_mini])
    for k in p[j:j+length_mini]:
      if k>=t:
        check=True;
      else:
        check=False
        break
    if check==False:
        results.append(colored('\nFor the substring match from loc '+str(j)+' having BCA as : '+bsa+' the match is INNACURATE','red',attrs=['bold', 'underline']))
    else:
        results.append(colored('\nFor the substring match from loc '+str(j)+' having BCA as : '+bsa+' the match is ACCURATE','green',attrs=['bold', 'underline']))

  return results

In [48]:
mainstr=final_S #Master string containing all DNA sequences
threshold=float(input('Enter threshold for accurate protein match: ')) #threshold for accurate protein match
direct = directMatch(mainstr, ministr, final_P,threshold) # calling the function directMatch

#print(colored("The Main String is : \n"+mainstr+'\n','yellow'))
print(colored("The Mini String is : \n"+ministr+'\n','blue'))
print(colored("The Base cell acc String is : \n"+str(final_P)+"\n",'magenta'))
print(colored('\n'+"*"*50+ '\n\nResults: ',attrs=['bold','underline']))
for i in direct:
    print(colored(i,attrs=['bold','underline']))

Enter threshold for accurate protein match: 99.97
Number of matches :  1622
The Mini String is : 
TAATG

The Base cell acc String is : 
[ 99.98  99.94 100.   ...  99.98 100.    99.96]


**************************************************

Results: 

For the substring match from loc 1679 having BCA as : [99.96 99.98 99.94 99.96 99.98] the match is INNACURATE

For the substring match from loc 2439 having BCA as : [99.98 99.94 99.96 99.94 99.94] the match is INNACURATE

For the substring match from loc 8950 having BCA as : [100.   100.    99.98 100.    99.98] the match is ACCURATE

For the substring match from loc 10160 having BCA as : [ 99.98 100.    99.98 100.   100.  ] the match is ACCURATE

For the substring match from loc 11640 having BCA as : [100.    99.96 100.    99.98 100.  ] the match is INNACURATE

For the substring match from loc 13483 having BCA as : [99.94 99.96 99.96 99.98 99.94] the match is INNACURATE

For the substring match from loc 14493 having BCA as : [100.    99.94  

For the substring match from loc 3080453 having BCA as : [99.94 99.94 99.98 99.94 99.98] the match is INNACURATE

For the substring match from loc 3083132 having BCA as : [99.98 99.94 99.98 99.96 99.98] the match is INNACURATE

For the substring match from loc 3083864 having BCA as : [ 99.96 100.   100.   100.    99.94] the match is INNACURATE

For the substring match from loc 3085061 having BCA as : [100.    99.98 100.   100.    99.98] the match is ACCURATE

For the substring match from loc 3086790 having BCA as : [ 99.98  99.96 100.    99.96  99.94] the match is INNACURATE

For the substring match from loc 3088468 having BCA as : [99.98 99.94 99.96 99.94 99.94] the match is INNACURATE

For the substring match from loc 3088614 having BCA as : [100.   100.    99.98  99.96 100.  ] the match is INNACURATE

For the substring match from loc 3093545 having BCA as : [100.    99.96 100.   100.    99.96] the match is INNACURATE

For the substring match from loc 3101998 having BCA as : [100.   

# Task 2

In [49]:
"""
Matching the dna sequences directly in order to distinguish between them based on MEAN base cell accuracy.
@param r: Master string
@param m: Randomly generated mini string of user defined length
@param p: Array of PHRED quality scores
@param t: Threshold value for accuracy of match

"""

def mean_directMatch(r, m, p,t):
  #global final_P
  temp=[]
  d=r.count(m)
  results2=[]
  length_mini=len(ministr) #length of ministring

  i=-1
  while d!=0:
    index=r.find(m,i+1)
    i=index
    if index not in temp:
      temp.append(index)
    d=d-1
    
  check=True
  for j in temp:
        sum=0
        for k in p[j:j+length_mini]:
            sum+=k
        avg=round(sum/length_mini,2)
        if avg>=t:
            results2.append(colored('\nFor the substring match from loc '+str(j)+' having mean BCA as : '+str(avg)+' the match is ACCURATE','green',attrs=['bold', 'underline']))
        else:
            results2.append(colored('\nFor the substring match from loc '+str(j)+' having mean BCA as : '+str(avg)+' the match is INNACURATE','red',attrs=['bold', 'underline']))
         
  return results2

In [50]:
#threshold shd change accordingly : as it MEAN base cell accuracy
threshold_2=float(input('Enter threshold for MEAN accurate protein match: ')) #threshold for accurate protein match
direct = mean_directMatch(mainstr, ministr, final_P,threshold_2) # calling the function directMatch

#print(colored("The Main String is : \n"+mainstr+'\n','yellow'))
print(colored("The Mini String is : \n"+ministr+'\n','blue'))
print(colored("The Base cell acc String is : \n"+str(final_P)+"\n",'magenta'))
print(colored('\n'+"*"*50+ '\n\nResults: ',attrs=['bold','underline']))
for i in direct:
    print(colored(i,attrs=['bold','underline']))

Enter threshold for MEAN accurate protein match: 99.95
The Mini String is : 
TAATG

The Base cell acc String is : 
[ 99.98  99.94 100.   ...  99.98 100.    99.96]


**************************************************

Results: 

For the substring match from loc 1679 having mean BCA as : 99.96 the match is ACCURATE

For the substring match from loc 2439 having mean BCA as : 99.95 the match is ACCURATE

For the substring match from loc 8950 having mean BCA as : 99.99 the match is ACCURATE

For the substring match from loc 10160 having mean BCA as : 99.99 the match is ACCURATE

For the substring match from loc 11640 having mean BCA as : 99.99 the match is ACCURATE

For the substring match from loc 13483 having mean BCA as : 99.96 the match is ACCURATE

For the substring match from loc 14493 having mean BCA as : 99.97 the match is ACCURATE

For the substring match from loc 14600 having mean BCA as : 99.96 the match is ACCURATE

For the substring match from loc 14682 having mean BCA as : 99.